image: tdeckers/docker-drone-sbt
git:
  path: github.com/tdeckers/acronym
script:
  - echo "build commands"
  - sbt compile
  - sbt test
  - sbt dist
clone:
  path: github.com/tdeckers/acronym
build:
  image: tdeckers/docker-drone-sbt
  commands:
    - echo "build commands"
    - sbt compile
    - sbt test
    - sbt dist
publish:
  docker:
    file: ./Dockerfile
    username: $$bintray_user
    password: $$bintray_api_key
    registry: $$bintray_registry
    repo: $$bintray_repo
    email: $$bintray_user_email
    tag: $$COMMIT
    
notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "https://api.ciscoshipped.io/webhooks/drone"
    on_success: true
    on_failure: true
