image: java:openjdk-8-jdk
git:
  path: github.com/tdeckers/acronym
script:
  - echo "build commands"
  - echo "no build command"
  - echo "no test command"
clone:
  path: github.com/tdeckers/acronym
build:
  image: java:openjdk-8-jdk
  commands:
    - echo "build commands"
    - echo "no build command"
    - echo "no test command"
publish:
  docker:
    file: ./Dockerfile
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    


notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "https://api.ciscoshipped.io/webhooks/drone"
    on_success: true
    on_failure: true
